### ISSUE TITLE
RootlyIncidentsPage & RootlyOverviewCard  not exported

### ISSUE THREAD

**Issue by avidelatm** [rootlyhq/backstage-plugin#2]
I've followed the steps to install the rootly plugin
 ```
yarn add @rootly/backstage-plugin
```

 but when trying to add `RootlyIncidentsPage` and `RootlyOverviewCard` , and runing `yarn tsc`  I get  the errors :

````
Module '"@rootly/backstage-plugin"' has no exported member 'RootlyIncidentsPage'.
Cannot find module '@rootly/backstage-plugin/src/components/Entity' or its corresponding type declarations.

````

I've tried this on my companies internal backstage,  but also I created a new backstage application from scratch to test this out with the same issue. 

Not sure if it's relevant, but I'm using node **lts/gallium**

**Comment by avidelatm** [comment]
Thanks @kwent , 

I already have those two lines in my code, as I copied them over from the readme documentation. 

I have  deleted them and paste them again ( this time from your comment), but it still didn't work.

As far as I can tell, the npmjs package for rootly doesn't export those two objects, and that is why this doesn't work.

This is what I see when I go through my node_modules for @rootly :
```
import * as _backstage_core_plugin_api from '@backstage/core-plugin-api';

declare const rootlyPlugin: _backstage_core_plugin_api.BackstagePlugin<{
    root: _backstage_core_plugin_api.RouteRef<undefined>;
}, {}>;
declare const RootlyPage: () => JSX.Element;

export { RootlyPage, rootlyPlugin };
```
I'm also attaching a screenshot for sake of clarity :) 
<img width="1628" alt="image" src="https://user-images.githubusercontent.com/13477864/176983218-88c52971-aaf5-4f5f-b214-4e44f34dbabd.png">

The version of the rootly backstage pluging that I seem to be using is `"@rootly/backstage-plugin": "^0.1.2"`

**Comment by kwent** [comment]
Hi @avidelatm, could you try` 0.1.7` with

```
import { RootlyIncidentsPage } from '@rootly/backstage-plugin';
import { RootlyOverviewCard } from '@rootly/backstage-plugin';
```

Regards

**Comment by drankou** [comment]
I am having the same issue, seems like the types declarations are missing in `/dist/index.d.ts`
