### ISSUE TITLE
Readme doesn't work

### ISSUE THREAD

**Issue by dncrews** [rootlyhq/backstage-plugin#45]
I generally wouldn't `@mention` someone directly, but @kwent I see you made the changes to the README.

[This package](https://github.com/rootlyhq/backstage-plugin/blob/7d613180fe1d9f122c5221d629d5338f174af387/README.md?plain=1#L48-L52) doesn't exist.

````md
Add the plugin to your backend app:

```bash
yarn add --cwd packages/backend @rootly/backstage-plugin-entity-processor
```
````

**Comment by kwent** [comment]
This version is not released yet. Refer to https://github.com/rootlyhq/backstage-plugin/blob/d4aea3d2e0b9def20e27543ff167bda390521693/README.md for now

**Comment by dncrews** [comment]
Thanks @kwent. I was able to figure that out from the commit history.

I just wanted you to see that your actual customer-base is affected, with the hope that you would be encouraged to revert your _official documentation_ back to something that works.

**Comment by dncrews** [comment]
Notably: since my comments, you have now also broken the old documentation that you have linked to in your comment. You do not currently have a functioning product in this repository, since you have published only _some_ of your packages, and you have listed your `-beta` as `latest`.

**Comment by kwent** [comment]
All packages has now been published.
