### ISSUE TITLE
Migrate to react-router stable

### ISSUE THREAD

**Issue by andrewthauer** [rootlyhq/backstage-plugin#8]
Backstage [release v1.6.0](https://github.com/backstage/backstage/releases/tag/v1.6.0) adds support for `react-router` v6 stable (instead of the pre-release). In order to migrate a backstage instance over to use the stable version, all plugins being must be updated to support stable version as per the [migration guide](https://backstage.io/docs/tutorials/react-router-stable-migration#for-plugin-authors). It would be great if the rootly plugin could be updated to support the stable version of `react-router` v6.

**Comment by kwent** [comment]
@andrewthauer Can you try https://www.npmjs.com/package/@rootly/backstage-plugin/v/0.3.0 ?

**Comment by andrewthauer** [comment]
@kwent - Yes, that version works. Thanks!

**Comment by andrewthauer** [comment]
@kwent - Although look at the package.json you updated the dependencies in place rather then making them `peerDependencies` and pinning for dev in `devDepedencies`. This works fine for us now that we've upgrade to the v6 stable, but anyone else still on the beta might have issues when they upgrade. If you follow the migration guide it will help make this work in both cases - https://backstage.io/docs/tutorials/react-router-stable-migration#for-plugin-authors.
